// AUTO-GENERATED by scripts/gen-hedgehog-deck.mjs. Do not edit by hand.
// Original names and illustrations for the Unhinged Hedgehogs first-generation deck.

export interface HedgehogCardPresentation {
  name: string;
  image: string;
}

export const UNHINGED_HEDGEHOG_CARDS = {
  "alluring-narwhal": {
    name: "Beguiling Bristle",
    image: "/themes/unhinged-hedgehogs/cards/alluring-narwhal.svg",
  },
  americorn: {
    name: "Star-Spangled Spiker",
    image: "/themes/unhinged-hedgehogs/cards/americorn.svg",
  },
  "angel-unicorn": {
    name: "Halo Hedge",
    image: "/themes/unhinged-hedgehogs/cards/angel-unicorn.svg",
  },
  "annoying-flying-unicorn": {
    name: "Airborne Nuisance",
    image: "/themes/unhinged-hedgehogs/cards/annoying-flying-unicorn.svg",
  },
  "baby-narwhal": {
    name: "Tiny Tusklet",
    image: "/themes/unhinged-hedgehogs/cards/baby-narwhal.svg",
  },
  "baby-unicorn-black": {
    name: "Midnight Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-black.svg",
  },
  "baby-unicorn-blue": {
    name: "Blueberry Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-blue.svg",
  },
  "baby-unicorn-brown": {
    name: "Acorn Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-brown.svg",
  },
  "baby-unicorn-death": {
    name: "Doom Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-death.svg",
  },
  "baby-unicorn-green": {
    name: "Mossy Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-green.svg",
  },
  "baby-unicorn-orange": {
    name: "Pumpkin Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-orange.svg",
  },
  "baby-unicorn-pink": {
    name: "Bubblegum Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-pink.svg",
  },
  "baby-unicorn-purple": {
    name: "Plum Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-purple.svg",
  },
  "baby-unicorn-rainbow": {
    name: "Prism Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-rainbow.svg",
  },
  "baby-unicorn-red": {
    name: "Firecracker Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-red.svg",
  },
  "baby-unicorn-white": {
    name: "Snowball Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-white.svg",
  },
  "baby-unicorn-yellow": {
    name: "Sunbeam Hedgelet",
    image: "/themes/unhinged-hedgehogs/cards/baby-unicorn-yellow.svg",
  },
  "back-kick": { name: "Prickle Punt", image: "/themes/unhinged-hedgehogs/cards/back-kick.svg" },
  "barbed-wire": {
    name: "Bramble Trouble",
    image: "/themes/unhinged-hedgehogs/cards/barbed-wire.svg",
  },
  "basic-unicorn-blue": {
    name: "Denim Darren",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-blue.svg",
  },
  "basic-unicorn-green": {
    name: "Vinyl Vera",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-green.svg",
  },
  "basic-unicorn-indigo": {
    name: "Emoji Edie",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-indigo.svg",
  },
  "basic-unicorn-orange": {
    name: "Pumpkin Pip",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-orange.svg",
  },
  "basic-unicorn-purple": {
    name: "Selfie Sylvie",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-purple.svg",
  },
  "basic-unicorn-red": {
    name: "Bearded Bert",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-red.svg",
  },
  "basic-unicorn-yellow": {
    name: "Disco Daisy",
    image: "/themes/unhinged-hedgehogs/cards/basic-unicorn-yellow.svg",
  },
  "black-knight-unicorn": {
    name: "Midnight Sentinel",
    image: "/themes/unhinged-hedgehogs/cards/black-knight-unicorn.svg",
  },
  "blatant-thievery": {
    name: "Brazen Burglary",
    image: "/themes/unhinged-hedgehogs/cards/blatant-thievery.svg",
  },
  "blinding-light": {
    name: "High-Beam Havoc",
    image: "/themes/unhinged-hedgehogs/cards/blinding-light.svg",
  },
  "broken-stable": {
    name: "Collapsed Burrow",
    image: "/themes/unhinged-hedgehogs/cards/broken-stable.svg",
  },
  "chainsaw-unicorn": {
    name: "Chainsaw Chester",
    image: "/themes/unhinged-hedgehogs/cards/chainsaw-unicorn.svg",
  },
  "change-of-luck": {
    name: "Fortune Flipper",
    image: "/themes/unhinged-hedgehogs/cards/change-of-luck.svg",
  },
  "classy-narwhal": {
    name: "Dapper Quilliam",
    image: "/themes/unhinged-hedgehogs/cards/classy-narwhal.svg",
  },
  "double-dutch": {
    name: "Double Trouble",
    image: "/themes/unhinged-hedgehogs/cards/double-dutch.svg",
  },
  "extra-tail": {
    name: "Bonus Bristles",
    image: "/themes/unhinged-hedgehogs/cards/extra-tail.svg",
  },
  "extremely-destructive-unicorn": {
    name: "Wrecking Bristle",
    image: "/themes/unhinged-hedgehogs/cards/extremely-destructive-unicorn.svg",
  },
  "extremely-fertile-unicorn": {
    name: "Prolific Prickles",
    image: "/themes/unhinged-hedgehogs/cards/extremely-fertile-unicorn.svg",
  },
  "ginormous-unicorn": {
    name: "Colossal Cuddler",
    image: "/themes/unhinged-hedgehogs/cards/ginormous-unicorn.svg",
  },
  "glitter-bomb": {
    name: "Confetti Catastrophe",
    image: "/themes/unhinged-hedgehogs/cards/glitter-bomb.svg",
  },
  "glitter-tornado": {
    name: "Sequin Cyclone",
    image: "/themes/unhinged-hedgehogs/cards/glitter-tornado.svg",
  },
  "good-deal": {
    name: "Prickly Windfall",
    image: "/themes/unhinged-hedgehogs/cards/good-deal.svg",
  },
  "greedy-flying-unicorn": {
    name: "Sky-High Hoarder",
    image: "/themes/unhinged-hedgehogs/cards/greedy-flying-unicorn.svg",
  },
  llamacorn: { name: "Hedge-Llama Drama", image: "/themes/unhinged-hedgehogs/cards/llamacorn.svg" },
  "magical-flying-unicorn": {
    name: "Arcane Aviator",
    image: "/themes/unhinged-hedgehogs/cards/magical-flying-unicorn.svg",
  },
  "magical-kittencorn": {
    name: "Kitten in Quills",
    image: "/themes/unhinged-hedgehogs/cards/magical-kittencorn.svg",
  },
  "majestic-flying-unicorn": {
    name: "Regal Glider",
    image: "/themes/unhinged-hedgehogs/cards/majestic-flying-unicorn.svg",
  },
  "mermaid-unicorn": {
    name: "Mermaid Hedge",
    image: "/themes/unhinged-hedgehogs/cards/mermaid-unicorn.svg",
  },
  "mystical-vortex": {
    name: "Burrow Vortex",
    image: "/themes/unhinged-hedgehogs/cards/mystical-vortex.svg",
  },
  "nanny-cam": { name: "Burrowcam", image: "/themes/unhinged-hedgehogs/cards/nanny-cam.svg" },
  narwhal: { name: "Pointy Porcupine", image: "/themes/unhinged-hedgehogs/cards/narwhal.svg" },
  "narwhal-torpedo": {
    name: "Quill Torpedo",
    image: "/themes/unhinged-hedgehogs/cards/narwhal-torpedo.svg",
  },
  neigh: { name: "Nope!", image: "/themes/unhinged-hedgehogs/cards/neigh.svg" },
  pandamonium: {
    name: "Panda Prickle Party",
    image: "/themes/unhinged-hedgehogs/cards/pandamonium.svg",
  },
  puppicorn: { name: "Puppy-Prickle", image: "/themes/unhinged-hedgehogs/cards/puppicorn.svg" },
  "queen-bee-unicorn": {
    name: "Queen Bristle",
    image: "/themes/unhinged-hedgehogs/cards/queen-bee-unicorn.svg",
  },
  "rainbow-aura": {
    name: "Spectrum Shield",
    image: "/themes/unhinged-hedgehogs/cards/rainbow-aura.svg",
  },
  "rainbow-mane": {
    name: "Technicolor Tuft",
    image: "/themes/unhinged-hedgehogs/cards/rainbow-mane.svg",
  },
  "rainbow-unicorn": {
    name: "Prism Prickles",
    image: "/themes/unhinged-hedgehogs/cards/rainbow-unicorn.svg",
  },
  "re-target": { name: "Aim Again", image: "/themes/unhinged-hedgehogs/cards/re-target.svg" },
  "reset-button": {
    name: "Big Red Do-Over",
    image: "/themes/unhinged-hedgehogs/cards/reset-button.svg",
  },
  rhinocorn: {
    name: "Rhino-Hedge Rampage",
    image: "/themes/unhinged-hedgehogs/cards/rhinocorn.svg",
  },
  "sadistic-ritual": {
    name: "Grim Grooming",
    image: "/themes/unhinged-hedgehogs/cards/sadistic-ritual.svg",
  },
  "seductive-unicorn": {
    name: "Charming Charmer",
    image: "/themes/unhinged-hedgehogs/cards/seductive-unicorn.svg",
  },
  "shabby-the-narwhal": {
    name: "Scruffy Quilliam",
    image: "/themes/unhinged-hedgehogs/cards/shabby-the-narwhal.svg",
  },
  "shake-up": { name: "Rattle the Burrow", image: "/themes/unhinged-hedgehogs/cards/shake-up.svg" },
  "shark-with-a-horn": {
    name: "Shark-Quill",
    image: "/themes/unhinged-hedgehogs/cards/shark-with-a-horn.svg",
  },
  slowdown: { name: "Molasses Mode", image: "/themes/unhinged-hedgehogs/cards/slowdown.svg" },
  "stabby-the-unicorn": {
    name: "Pointy Pete",
    image: "/themes/unhinged-hedgehogs/cards/stabby-the-unicorn.svg",
  },
  "summoning-ritual": {
    name: "Circle of Quills",
    image: "/themes/unhinged-hedgehogs/cards/summoning-ritual.svg",
  },
  "super-neigh": {
    name: "Absolutely Nope!",
    image: "/themes/unhinged-hedgehogs/cards/super-neigh.svg",
  },
  "swift-flying-unicorn": {
    name: "Speedy Sky-Spike",
    image: "/themes/unhinged-hedgehogs/cards/swift-flying-unicorn.svg",
  },
  "targeted-destruction": {
    name: "Precision Prick",
    image: "/themes/unhinged-hedgehogs/cards/targeted-destruction.svg",
  },
  "the-great-narwhal": {
    name: "Grand Quilliam",
    image: "/themes/unhinged-hedgehogs/cards/the-great-narwhal.svg",
  },
  "tiny-stable": {
    name: "Pocket Burrow",
    image: "/themes/unhinged-hedgehogs/cards/tiny-stable.svg",
  },
  "two-for-one": {
    name: "One Prick, Two Pops",
    image: "/themes/unhinged-hedgehogs/cards/two-for-one.svg",
  },
  "unfair-bargain": {
    name: "Lopsided Swap",
    image: "/themes/unhinged-hedgehogs/cards/unfair-bargain.svg",
  },
  "unicorn-lasso": {
    name: "Hedgehog Hook",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-lasso.svg",
  },
  "unicorn-on-the-cob": {
    name: "Cob-Hog",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-on-the-cob.svg",
  },
  "unicorn-phoenix": {
    name: "Phoenix Prickle",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-phoenix.svg",
  },
  "unicorn-poison": {
    name: "Quill Tonic",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-poison.svg",
  },
  "unicorn-shrinkray": {
    name: "Pocket-Sized Panic",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-shrinkray.svg",
  },
  "unicorn-swap": {
    name: "Prickle Trade",
    image: "/themes/unhinged-hedgehogs/cards/unicorn-swap.svg",
  },
  yay: { name: "Heck Yes!", image: "/themes/unhinged-hedgehogs/cards/yay.svg" },
  "zombie-unicorn": {
    name: "Undead Underbrush",
    image: "/themes/unhinged-hedgehogs/cards/zombie-unicorn.svg",
  },
} as const satisfies Record<string, HedgehogCardPresentation>;
