export const HEDGEHOG_NAMES = {
  "alluring-narwhal": "Beguiling Bristle",
  americorn: "Star-Spangled Spiker",
  "angel-unicorn": "Halo Hedge",
  "annoying-flying-unicorn": "Airborne Nuisance",
  "baby-narwhal": "Tiny Tusklet",
  "baby-unicorn-black": "Midnight Hedgelet",
  "baby-unicorn-blue": "Blueberry Hedgelet",
  "baby-unicorn-brown": "Acorn Hedgelet",
  "baby-unicorn-death": "Doom Hedgelet",
  "baby-unicorn-green": "Mossy Hedgelet",
  "baby-unicorn-orange": "Pumpkin Hedgelet",
  "baby-unicorn-pink": "Bubblegum Hedgelet",
  "baby-unicorn-purple": "Plum Hedgelet",
  "baby-unicorn-rainbow": "Prism Hedgelet",
  "baby-unicorn-red": "Firecracker Hedgelet",
  "baby-unicorn-white": "Snowball Hedgelet",
  "baby-unicorn-yellow": "Sunbeam Hedgelet",
  "back-kick": "Prickle Punt",
  "barbed-wire": "Bramble Trouble",
  "basic-unicorn-blue": "Denim Darren",
  "basic-unicorn-green": "Vinyl Vera",
  "basic-unicorn-indigo": "Emoji Edie",
  "basic-unicorn-orange": "Pumpkin Pip",
  "basic-unicorn-purple": "Selfie Sylvie",
  "basic-unicorn-red": "Bearded Bert",
  "basic-unicorn-yellow": "Disco Daisy",
  "black-knight-unicorn": "Midnight Sentinel",
  "blatant-thievery": "Brazen Burglary",
  "blinding-light": "High-Beam Havoc",
  "broken-stable": "Collapsed Burrow",
  "chainsaw-unicorn": "Chainsaw Chester",
  "change-of-luck": "Fortune Flipper",
  "classy-narwhal": "Dapper Quilliam",
  "double-dutch": "Double Trouble",
  "extra-tail": "Bonus Bristles",
  "extremely-destructive-unicorn": "Wrecking Bristle",
  "extremely-fertile-unicorn": "Prolific Prickles",
  "ginormous-unicorn": "Colossal Cuddler",
  "glitter-bomb": "Confetti Catastrophe",
  "glitter-tornado": "Sequin Cyclone",
  "good-deal": "Prickly Windfall",
  "greedy-flying-unicorn": "Sky-High Hoarder",
  llamacorn: "Hedge-Llama Drama",
  "magical-flying-unicorn": "Arcane Aviator",
  "magical-kittencorn": "Kitten in Quills",
  "majestic-flying-unicorn": "Regal Glider",
  "mermaid-unicorn": "Mermaid Hedge",
  "mystical-vortex": "Burrow Vortex",
  "nanny-cam": "Burrowcam",
  narwhal: "Pointy Porcupine",
  "narwhal-torpedo": "Quill Torpedo",
  neigh: "Nope!",
  pandamonium: "Panda Prickle Party",
  puppicorn: "Puppy-Prickle",
  "queen-bee-unicorn": "Queen Bristle",
  "rainbow-aura": "Spectrum Shield",
  "rainbow-mane": "Technicolor Tuft",
  "rainbow-unicorn": "Prism Prickles",
  "re-target": "Aim Again",
  "reset-button": "Big Red Do-Over",
  rhinocorn: "Rhino-Hedge Rampage",
  "sadistic-ritual": "Grim Grooming",
  "seductive-unicorn": "Charming Charmer",
  "shabby-the-narwhal": "Scruffy Quilliam",
  "shake-up": "Rattle the Burrow",
  "shark-with-a-horn": "Shark-Quill",
  slowdown: "Molasses Mode",
  "stabby-the-unicorn": "Pointy Pete",
  "summoning-ritual": "Circle of Quills",
  "super-neigh": "Absolutely Nope!",
  "swift-flying-unicorn": "Speedy Sky-Spike",
  "targeted-destruction": "Precision Prick",
  "the-great-narwhal": "Grand Quilliam",
  "tiny-stable": "Pocket Burrow",
  "two-for-one": "One Prick, Two Pops",
  "unfair-bargain": "Lopsided Swap",
  "unicorn-lasso": "Hedgehog Hook",
  "unicorn-on-the-cob": "Cob-Hog",
  "unicorn-phoenix": "Phoenix Prickle",
  "unicorn-poison": "Quill Tonic",
  "unicorn-shrinkray": "Pocket-Sized Panic",
  "unicorn-swap": "Prickle Trade",
  yay: "Heck Yes!",
  "zombie-unicorn": "Undead Underbrush",
};
