/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as LobbyGameIdRouteImport } from './routes/lobby.$gameId'
import { Route as ApiStreamGameIdRouteImport } from './routes/api/stream.$gameId'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyGameIdRoute = LobbyGameIdRouteImport.update({
  id: '/lobby/$gameId',
  path: '/lobby/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamGameIdRoute = ApiStreamGameIdRouteImport.update({
  id: '/api/stream/$gameId',
  path: '/api/stream/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/api/stream/$gameId': typeof ApiStreamGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/api/stream/$gameId': typeof ApiStreamGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/lobby/$gameId': typeof LobbyGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/api/stream/$gameId': typeof ApiStreamGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/lobby/$gameId'
    | '/play/$gameId'
    | '/api/stream/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/lobby/$gameId'
    | '/play/$gameId'
    | '/api/stream/$gameId'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/lobby/$gameId'
    | '/play/$gameId'
    | '/api/stream/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  LobbyGameIdRoute: typeof LobbyGameIdRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  ApiStreamGameIdRoute: typeof ApiStreamGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$gameId': {
      id: '/lobby/$gameId'
      path: '/lobby/$gameId'
      fullPath: '/lobby/$gameId'
      preLoaderRoute: typeof LobbyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$gameId': {
      id: '/api/stream/$gameId'
      path: '/api/stream/$gameId'
      fullPath: '/api/stream/$gameId'
      preLoaderRoute: typeof ApiStreamGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  LobbyGameIdRoute: LobbyGameIdRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  ApiStreamGameIdRoute: ApiStreamGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
